### ISSUE TITLE
[Bug] head.mrb outlined in validator docs does not exist 

### ISSUE THREAD

**Issue by nonfungible-dev** [aptos-labs/aptos-core#3192]
# 🐛 Bug

When following the instructions to set up a new Validator (https://aptos.dev/nodes/validator-node/run-validator-node-using-docker), the instructions say to download `head.mrb`.  Doing so returns a 404 error:

## Steps to reproduce

```bash
$  curl https://raw.githubusercontent.com/aptos-labs/aptos-core/testnet/aptos-move/framework/releases/head.mrb --output framework.mrb

$ cat framework.mrb
404: Not Found
```

## Error message or problem
Trying to invoke the next step of the validator setup with this incorrect mrb file results in the following error:

```
$ aptos genesis generate-genesis --local-repository-dir $APTOS_DIR --output-dir $APTOS_DIR
{
  "Error": "Unexpected error: unexpected end of input"
}
```

## Expected Behavior

The documentation should point to a valid `head.mrb` file so that we can set up our validators

**Comment by davidiw** [comment]
fixed, thanks for the notice!

**Comment by bmalepaty** [comment]
@nonfungible-dev Is this solved for you.
I followed you steps:
Did "curl https://raw.githubusercontent.com/aptos-labs/aptos-core/testnet/aptos-move/framework/releases/head.mrb --output framework.mrb"

And I'm still getting this:
$ aptos genesis generate-genesis --local-repository-dir $APTOS_DIR --output-dir $APTOS_DIR
{
  "Error": "Unexpected error: unexpected end of input"
}
